DEFAULT_BRANCH: main

ENABLE_LINTERS:
  - HTML_DJLINT

SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
PRINT_ALPACA: false

APPLY_FIXES: all

HTML_DJLINT_FILE_EXTENSIONS:
  - .ftl
  - .css
HTML_DJLINT_FILTER_REGEX_INCLUDE: themes/oaf/
