initContainers:
 - name: init-myservice
   image: oaftech.azurecr.io/oneacrefund/keycloak-themes:latest
   volumeMounts:
   - name: themes
     mountPath: /usr/keycloak/themes

extraVolumeMounts:
- name: themes
  mountPath: /opt/bitnami/keycloak/themes

extraVolumes:
- name: themes
  persistentVolumeClaim:
    claimName: keycloak-themes
