apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-themes
  namespace: tools
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: oaf-shared
