apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-themes
  namespace: tools
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100M
  storageClassName: oaf-shared
